import React from 'react';
import { useFloodStore } from './store';
import { useMQTT } from './hooks/useMQTT';
import { useSensorData } from './hooks/useSensorData';
import { SensorList } from './components/SensorList';
import { AlertPanel } from './components/AlertPanel';
import { Map } from './components/Map';
import { TrendChart } from './components/TrendChart';
import { levelForWater } from './types/alert';

const seed = [{ id: 'node-01', name: 'Cảm biến bờ sông', zoneId: 'zone-01', status: 'online' as const, waterCm: 128, rainMm: 8, batteryPct: 94, lat: 10.78, lng: 106.69, updatedAt: new Date().toISOString() }];
export function App() { const sensors = useSensorData(); const history = useFloodStore(s => s.history); const upsert = useFloodStore(s => s.upsertSensor); const { connected } = useMQTT(); const primary = sensors[0]; React.useEffect(() => { if (!sensors.length) seed.forEach(upsert); }, [sensors.length, upsert]); const warningCount = sensors.filter(s => levelForWater(s.waterCm ?? 0) !== 'normal').length; return <main className="min-h-screen bg-slate-950 text-slate-100"><header className="sticky top-0 z-20 border-b border-slate-800 bg-slate-950/95 px-4 py-4 backdrop-blur md:px-6"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><h1 className="text-xl font-semibold">Flood Alert & Monitoring</h1><p className="text-sm text-slate-400">Giám sát lũ theo thời gian thực</p></div><span className={`rounded-full border px-3 py-1 text-xs ${connected ? 'border-emerald-800 text-emerald-400' : 'border-slate-700 text-slate-500'}`}>● MQTT {connected ? 'connected' : 'offline'}</span></div></header><div className="mx-auto grid max-w-7xl gap-4 p-4 md:p-6"><section className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><p className="text-xs text-slate-500">Cảm biến</p><p className="mt-1 text-2xl font-bold">{sensors.length}</p></div><div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><p className="text-xs text-slate-500">Cảnh báo</p><p className="mt-1 text-2xl font-bold">{warningCount}</p></div><div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><p className="text-xs text-slate-500">Mực nước cao nhất</p><p className="mt-1 text-2xl font-bold">{Math.max(0, ...sensors.map(s => s.waterCm ?? 0))} <span className="text-sm font-normal text-slate-400">cm</span></p></div></section><section className="grid gap-4 lg:grid-cols-[1.5fr_1fr]"><div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><h2 className="mb-3 font-semibold">Bản đồ cảm biến</h2><Map sensors={sensors} /></div><AlertPanel /></section><section className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">Xu hướng realtime</h2><span className="text-xs text-slate-500">{primary?.name ?? 'Chưa có cảm biến'}</span></div><TrendChart data={primary ? history[primary.id] ?? [] : []} /></section><section><h2 className="mb-3 font-semibold">Thiết bị</h2><SensorList sensors={sensors} /></section></div></main>; }
